steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/aba-run/aba-run:${SHORT_SHA}
      - -f
      - aba-run/Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/aba-run/aba-run:${SHORT_SHA}
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - aba-run
      - --image
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/aba-run/aba-run:${SHORT_SHA}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - "8080"
images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/aba-run/aba-run:${SHORT_SHA}
substitutions:
  _REGION: europe-west1
options:
  logging: CLOUD_LOGGING_ONLY
